### ISSUE TITLE
Avoid secrets leakage when displaying help output

### ISSUE THREAD

**Issue by nixwiz** [sensu-community/sensu-plugin-sdk#35]
When displaying --help output whether intentionally or when an error has occurred, if a secret is present as an environment variable assignable in PluginConfigOption, it could possibly be leaked.

One possible solution would be to add a PluginConfigOption boolean called 'secret' that when set to true would not print the default values in those cases.

**Comment by jspaleta** [comment]
This maybe a limitation in the cobra package that is being used to generate the usage message,  I don't see a way to override the printout of the default value in the usage message if the default is non-empty.

Other than that, I have to wonder, do we need to do the call to 
viper.SetDefault(opt.Argument, opt.Default)   at all in func setupFlag?

I believe this is the problematic call we are replacing the fallback Default with the argument. My understanding of the logic is because the env_var is already bound to the argument, the default won't be used.  I don't think we technically need this at all for any argument.

I think it might be sufficient to remove that 1 line. 

How can a build a local copy of the influxdb handler against a branch of this sdk with the change?

**Comment by jspaleta** [comment]
Okay it took a bit to figure out.. but i think i have it. PR in bound
